export const teaDesignTokens = {
  spacing: {
    base: '0.5rem',
    xxs: '0.125rem',
    xs: '0.25rem',
    sm: '0.5rem',
    md: '0.75rem',
    lg: '1rem',
    xl: '1.5rem',
    xxl: '2rem',
    section: '5.5rem',
    1: '0.25rem',
    2: '0.5rem',
    3: '0.75rem',
    4: '1rem',
    5: '1.25rem',
    6: '1.5rem',
  },
  typography: {
    bodySize: '1rem',
    bodyLineHeight: '1.5',
    sansFamily:
      "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI Variable', 'Segoe UI', 'PingFang SC', 'Microsoft YaHei UI', 'Microsoft YaHei', 'Noto Sans CJK SC', 'Noto Sans SC', system-ui, sans-serif",
    displayFamily:
      "'SF Pro Rounded', ui-rounded, -apple-system, BlinkMacSystemFont, 'PingFang SC', system-ui, sans-serif",
    monoFamily: "'JetBrains Mono Variable', 'SFMono-Regular', Menlo, Monaco, monospace",
  },
  control: {
    compactHeight: '2.25rem',
    defaultHeight: '2.5rem',
    primaryHeight: '2.5rem',
  },
  radius: {
    menu: '8px',
    inline: '6px',
    card: '12px',
    control: '9999px',
    overlay: '12px',
  },
  colors: {
    accent: '#000000',
    danger: '#c43d46',
    success: '#377a32',
    warning: '#a26a16',
    canvas: '#ffffff',
    surface: '#ffffff',
    panel: '#fafafa',
    line: '#e5e5e5',
    lineStrong: '#d4d4d4',
    focus: 'rgb(59 130 246 / 50%)',
  },
  elevation: {
    overlay: 'none',
  },
} as const
