export const teaDesignTokens = {
  spacing: {
    base: '0.25rem',
    xxs: '0.25rem',
    xs: '0.5rem',
    sm: '0.75rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    xxl: '3rem',
    section: '6rem',
    1: '0.25rem',
    2: '0.5rem',
    3: '0.75rem',
    4: '1rem',
    5: '1.25rem',
    6: '1.5rem',
  },
  typography: {
    bodySize: '1rem',
    bodyLineHeight: '1.5',
    sansFamily:
      "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI Variable', 'Segoe UI', 'PingFang SC', 'Microsoft YaHei UI', 'Microsoft YaHei', 'Noto Sans CJK SC', 'Noto Sans SC', system-ui, sans-serif",
    displayFamily:
      "'Cal Sans', 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', system-ui, sans-serif",
    monoFamily: "'JetBrains Mono Variable', 'SFMono-Regular', Menlo, Monaco, monospace",
    displayXl: { size: '64px', weight: 600, lineHeight: '1.05', letterSpacing: '-2px' },
    displayLg: { size: '48px', weight: 600, lineHeight: '1.1', letterSpacing: '-1.5px' },
    displayMd: { size: '36px', weight: 600, lineHeight: '1.15', letterSpacing: '-1px' },
    displaySm: { size: '28px', weight: 600, lineHeight: '1.2', letterSpacing: '-0.5px' },
    titleLg: { size: '22px', weight: 600, lineHeight: '1.3', letterSpacing: '-0.3px' },
    titleMd: { size: '18px', weight: 600, lineHeight: '1.4', letterSpacing: '0' },
    titleSm: { size: '16px', weight: 600, lineHeight: '1.4', letterSpacing: '0' },
    bodySm: { size: '14px', weight: 400, lineHeight: '1.5', letterSpacing: '0' },
    caption: { size: '13px', weight: 500, lineHeight: '1.4', letterSpacing: '0' },
    code: { size: '14px', weight: 400, lineHeight: '1.5', letterSpacing: '0' },
    button: { size: '14px', weight: 600, lineHeight: '1', letterSpacing: '0' },
    navLink: { size: '14px', weight: 500, lineHeight: '1.4', letterSpacing: '0' },
  },
  control: {
    compactHeight: '2.25rem',
    defaultHeight: '2.5rem',
    primaryHeight: '2.5rem',
  },
  radius: {
    menu: '8px',
    inline: '6px',
    card: '12px',
    control: '8px',
    pill: '9999px',
    overlay: '12px',
  },
  colors: {
    primary: '#111111',
    primaryActive: '#242424',
    primaryDisabled: '#e5e7eb',
    ink: '#111111',
    body: '#374151',
    muted: '#6b7280',
    mutedSoft: '#898989',
    accent: '#111111',
    onAccent: '#ffffff',
    danger: '#ef4444',
    onDanger: '#ffffff',
    success: '#10b981',
    warning: '#f59e0b',
    canvas: '#ffffff',
    surface: '#ffffff',
    panel: '#f8f9fa',
    surfaceCard: '#f5f5f5',
    surfaceStrong: '#e5e7eb',
    surfaceDark: '#101010',
    surfaceDarkElevated: '#1a1a1a',
    scrim: '#000000',
    codeSurface: '#f8f9fa',
    codeFg: '#111111',
    inverse: '#111111',
    onInverse: '#ffffff',
    line: '#e5e7eb',
    lineSoft: '#f3f4f6',
    lineStrong: '#e5e7eb',
    focus: 'rgb(59 130 246 / 50%)',
    onPrimary: '#ffffff',
    onDark: '#ffffff',
    onDarkSoft: '#a1a1aa',
    brandAccent: '#3b82f6',
    badgeOrange: '#fb923c',
    badgePink: '#ec4899',
    badgeViolet: '#8b5cf6',
    badgeEmerald: '#34d399',
  },
  elevation: {
    overlay: 'none',
  },
  themePreferences: ['system', 'light', 'dark'],
} as const
