import type { ComposerTranslation } from 'vue-i18n'

import type { TaskItem } from './contracts'

export function createTaskDemoData(t: ComposerTranslation): TaskItem[] {
  return [
    {
      id: 'MSG-1042',
      title: t('tasks.mock.onboarding.title'),
      description: t('tasks.mock.onboarding.description'),
      status: 'inProgress',
      priority: 'high',
      progress: 62,
      assignee: 'Anna',
      dueLabel: t('tasks.dates.today'),
      tags: ['Customer', 'Onboarding'],
      source: {
        kind: 'message',
        name: 'Customer feedback',
        context: t('tasks.mock.onboarding.source'),
      },
      comments: [
        {
          id: 'comment-onboarding-1',
          author: 'Anna',
          body: t('tasks.mock.onboarding.comment'),
          createdAtLabel: t('tasks.dates.minutesAgo', { count: 18 }),
        },
      ],
      updatedAtLabel: t('tasks.dates.minutesAgo', { count: 18 }),
    },
    {
      id: 'GH-287',
      title: t('tasks.mock.avatar.title'),
      description: t('tasks.mock.avatar.description'),
      status: 'inProgress',
      priority: 'medium',
      progress: 74,
      assignee: t('tasks.people.you'),
      dueLabel: t('tasks.dates.tomorrow'),
      tags: ['Frontend', 'Release'],
      source: {
        kind: 'plugin',
        name: 'GitHub',
        context: 'tea-desktop #287',
      },
      comments: [
        {
          id: 'comment-avatar-1',
          author: 'Lin',
          body: t('tasks.mock.avatar.comment'),
          createdAtLabel: t('tasks.dates.hoursAgo', { count: 2 }),
        },
      ],
      updatedAtLabel: t('tasks.dates.hoursAgo', { count: 2 }),
    },
    {
      id: 'LOCAL-018',
      title: t('tasks.mock.demo.title'),
      description: t('tasks.mock.demo.description'),
      status: 'inProgress',
      priority: 'high',
      progress: 46,
      assignee: t('tasks.people.you'),
      dueLabel: t('tasks.dates.today'),
      tags: ['Demo', 'Product'],
      source: {
        kind: 'local',
        name: t('tasks.sources.localWorkspace'),
        context: t('tasks.mock.demo.source'),
      },
      comments: [],
      updatedAtLabel: t('tasks.dates.hoursAgo', { count: 3 }),
    },
    {
      id: 'MON-404',
      title: t('tasks.mock.heartbeat.title'),
      description: t('tasks.mock.heartbeat.description'),
      status: 'inbox',
      priority: 'high',
      progress: 12,
      assignee: 'Maya',
      dueLabel: t('tasks.dates.sep4'),
      tags: ['Reliability'],
      source: {
        kind: 'plugin',
        name: 'Cloud Monitor',
        context: t('tasks.mock.heartbeat.source'),
      },
      comments: [],
      updatedAtLabel: t('tasks.dates.hoursAgo', { count: 5 }),
    },
    {
      id: 'LOCAL-012',
      title: t('tasks.mock.permissions.title'),
      description: t('tasks.mock.permissions.description'),
      status: 'inbox',
      priority: 'medium',
      progress: 20,
      assignee: 'Iris',
      dueLabel: t('tasks.dates.nextMonday'),
      tags: ['Copy', 'Security'],
      source: {
        kind: 'local',
        name: t('tasks.sources.localWorkspace'),
        context: t('tasks.mock.permissions.source'),
      },
      comments: [],
      updatedAtLabel: t('tasks.dates.yesterday'),
    },
    {
      id: 'JIRA-681',
      title: t('tasks.mock.contract.title'),
      description: t('tasks.mock.contract.description'),
      status: 'review',
      priority: 'high',
      progress: 90,
      assignee: t('tasks.people.you'),
      dueLabel: t('tasks.dates.sep4'),
      tags: ['Architecture', 'API'],
      source: {
        kind: 'plugin',
        name: 'Jira Cloud',
        context: 'Platform / JIRA-681',
      },
      comments: [
        {
          id: 'comment-contract-1',
          author: 'Chen',
          body: t('tasks.mock.contract.comment'),
          createdAtLabel: t('tasks.dates.hoursAgo', { count: 1 }),
        },
      ],
      updatedAtLabel: t('tasks.dates.hoursAgo', { count: 1 }),
    },
    {
      id: 'MSG-988',
      title: t('tasks.mock.planning.title'),
      description: t('tasks.mock.planning.description'),
      status: 'review',
      priority: 'medium',
      progress: 84,
      assignee: 'Luo',
      dueLabel: t('tasks.dates.sep6'),
      tags: ['Planning'],
      source: {
        kind: 'message',
        name: 'Product planning',
        context: t('tasks.mock.planning.source'),
      },
      comments: [],
      updatedAtLabel: t('tasks.dates.hoursAgo', { count: 4 }),
    },
    {
      id: 'MSG-971',
      title: t('tasks.mock.retrospective.title'),
      description: t('tasks.mock.retrospective.description'),
      status: 'done',
      priority: 'low',
      progress: 100,
      assignee: 'Chen',
      dueLabel: t('tasks.dates.sep2'),
      tags: ['Launch'],
      source: {
        kind: 'message',
        name: 'Launch room',
        context: t('tasks.mock.retrospective.source'),
      },
      comments: [],
      updatedAtLabel: t('tasks.dates.yesterday'),
    },
  ]
}
